language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.1
  - android-23
  - extra-android-m2repository
script:
- ./gradlew -PbintrayUser="${bintrayUser}" -PbintrayKey="${bintrayKey}" bintrayUpload
  --stacktrace --info
env:
  global:
  - secure: odFavDRoNBc8fAKtCxntatwjBPbOBPlzwcOaLKeFR+MouSACyQXiLjkGwLT+8dx2Y2FSxglzrDmbbTUTbaL9/NkBqld35p71Eizzdl3XraKHjUZ42MajNhTPw+jBDOl+Jn2H26Rozff8u9Rw6AZekMktqsMIM+al4Khtuyi0C/LvyiGy1/95demj9MbMa9wDVEYYTQ8ImA6lNTWWLHi/yOgmIlIknKiwO3sPEBIdJqE4QF4svjiRD4/XG7BFxga0GWQ5DYY0Fla5BUKRBoeKnMfHNatULULN+eC/fPTjsZLVd1tBbEd+gzwVwmKf2V8Oie6/IXjigSASxNexIs1BkCWNS8zyd2fA8Lv4psCf5AEYuOhtewGyNYMG5EUYfUmC0pG1sT181C2Db0osoGPHi275lzb+y6JcNiiRv2mGHclTebnrQdj9xzLmPzeMXh7Cr8oKJlA8L3G4R9s2uW3AEV6w1p/Xa60whtNWTjiIWQ7O2fwl5aWtLCFBH9hC19fBTmwTTvANSBzr5Rv/mokVwFFIFffCVZonRi5k01iXeuruBZG6giA1xm7/Sc3Ck4xoD/cv0vVjZUKWhWo0/ZdmZAxsUostur2Lpma4OIIL43HWmZVr7vCYtu1NkZ0x95dL72sp2vsmj4miZVSCxQFL3NYHmKofIBICZtBO8k7LE8g=
  - secure: Lv/tTpnzmLC2B3eiJOWEwqllYxuaDoUV0/pU4XIRiAq3nNgCobS66JR5P0v90s/QVPPwf1CZGGjVcfi+i9rb9xCkHCI7VvzSr878bgghfG5QVst1bTGsZzqEPEQxGzA1xuonF6sn84EKI+K9aGDvU+qP2yyEkRLDgMDWvl21lFfUBRzee+lGYNZOmJWMHYO/dlgU+9DZz162M8XQB8bJVIzAcEY7D1qQJVpzCtBhGrfJUlATdbWZp4EynNCAa+u9BilHRVbo4Ii+vjy8sc0DabM1NQW09tv/tylfB4Svfaj/ri1wWg9qH7KJvOL9nZWlo1ZS1h/sKgWCTykGdiolCF6Ns1M4HRCW6xkEeby5IutrfzCE6pxBRu7KWcjLUxMmkdwLCAiiv8CikbR+pl8N03aewQf9P/GEp9EJSY72DHbk5IZ2sQEZ2gond91C1JFzy9GyROu91IEvFemFAh7fdIIz1W+RWQedv4xtTDueJqnYlPdW1bGMPzNLGQOoFPQCqzDOkU0LP6eMZVqGB+y/h/EwOEFIUdho7Wmb3cd5ErfwyikH46UZMDrrndmjRTzV2/5gRzmNb135zu56YinFDZP8fv2Y28ECmzp9cqR7uZyUFIrEYqoIVUJ70ZrivKV7dT/BXWKFQCflzBhWeqhPDHsbu495bfrjqyG6R98rTIA=
